name: Deploy to Kakao Cloud

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ==========================
    # FRONTEND DOCKER IMAGE BUILD
    # ==========================
    - name: Build Frontend Image
      run: |
        docker build -t ghcr.io/juin925/schedule-frontend:latest ./frontend

    # ==========================
    # BACKEND DOCKER IMAGE BUILD
    # ==========================
    - name: Build Backend Image
      run: |
        docker build -t ghcr.io/juin925/schedule-backend:latest ./backend

    # ==========================
    # Login to GHCR
    # ==========================
    - name: Login to GHCR
      run: |
        echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u juin925 --password-stdin

    # Push images
    - name: Push Images
      run: |
        docker push ghcr.io/juin925/schedule-frontend:latest
        docker push ghcr.io/juin925/schedule-backend:latest

    # ==========================
    # Deploy to Kakao Cloud
    # ==========================
    - name: Deploy on Kakao Cloud
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          cd /app/schedule-app
          docker compose pull
          docker compose up -d
          docker image prune -f
